### ISSUE TITLE
ObjectNotInLowlevelStorageException: no path in db registry 

### ISSUE THREAD

**Issue by ThomasEdelburg** [fcrepo/fcrepo#1932]
Sorry for asking here, but I haven't found a better place. Perhaps one of you has already had this error. 
The current version is Fedora 3.8.1. 

We have the following error:
Caused by: org.fcrepo.server.errors.ObjectNotInLowlevelStorageException: no path in db registry for [CH-000071-X:aip-01-0000647832-0001+ZIP+ZIP.0]

The AIP is correctly entered in the database table OBJECTPATHS (85000 rows).

In the database table DATASTREAMPATHS (only 25000 rows) the AIP is not available.

A rebuild.sh (a fresh Database and re-reading the AIPs with 1 and 2) does not solve the problem either.
Some AIPs are missing and some are there.

Is there anyone who could help with this problem, what can we do?
Many thanks Thomas

**Comment by bcail** [comment]
if you search your datastream file store for that ZIP file, do you see it?

**Comment by ThomasEdelburg** [comment]
thanks, yes all datastreams are in the correct folders and subfolders no zip file is missing

**Comment by Surfrdan** [comment]
I'm closing this due to a lack of activity. If you are still experiencing file loss, then please re-open for further assistance
