### ISSUE TITLE
acl cache not invalidated when acl rules are updated on disk

### ISSUE THREAD

**Issue by nicolasfranck** [fcrepo/fcrepo#1961]
When I create acl rules into a `/fcr:acl` subcontainer,
those rules are applied immediately.

But when I try to update those rules, it takes a while
before those updates are applied. Waiting helps,
or even restarting.

e.g.

1. I make sure that "user1" can read, write and create new subcontainer within `/fcrepo/rest/foo` (`acl:Read`, `acl:Write` and `acl:Append`)
2. "user1" can now create subcontainer within `/fcrepo/rest/foo` 
3. I update the acl rules so only `acl:Read` remains
4. "user1" can still create subcontainers within `/fcrepo/rest/foo`
5. restart fedora
6. "user1" can now only read from `/fcrepo/rest/foo`

After some searching, I discovered that the `WebACFilter` uses a [cache](https://github.com/fcrepo/fcrepo/blob/main/fcrepo-configs/src/main/java/org/fcrepo/config/FedoraPropsConfig.java#L128)
when fetching the acl rules for a certain resource.

If I set these properties

```
fcrepo.cache.webac.acl.size.entries=0
fcrepo.cache.webac.acl.timeout.minutes=0
```

the behaviour becomes normal, and the WebACFilter uses
the acl rules from disk.

So I'm guessing that the cache entry for that resource is never
cleared when the underlying acl rules are updated.

See also https://github.com/fcrepo/fcrepo/pull/1911

**Comment by whikloj** [comment]
@nicolasfranck I see what I missed here, there will be a PR coming soon.
https://fedora-repository.atlassian.net/browse/FCREPO-3795

**Comment by dbernstein** [comment]
The above issue has been resolved.

**Comment by nicolasfranck** [comment]
Thanks!
