### ISSUE TITLE
Sorry if i'm asking in the wrong place, How can i install the wayland-server package?

### ISSUE THREAD

**Issue by itaysharir** [fcrepo/fcrepo#2004]
I'm trying to install Hyprland on the latest version of fedora. i followed the instructions but when i try to build it it says i need wayland-server. I tried to install that with "sudo dnf install wayland-server" but the package isn't there. How can i install it? 
Thanks in advance!

**Comment by bbpennel** [comment]
I think you might be looking for the other Fedora, the operating system?
https://getfedora.org/
This git repository is for the Fedora repository platform, which is a preservation focus linked data/http API:
https://duraspace.org/fedora/

**Comment by itaysharir** [comment]
Oh i'm so sorry!
