### ISSUE TITLE
Return Transaction ID on 409: Conflict

### ISSUE THREAD

**Issue by tomwrobel** [fcrepo/fcrepo#2040]
When I attempt to perform an action on an object that is locked by another transaction, I get a 409 Transaction: Conflict error.

This error does not specify the id of the open transaction.

It is often the case that I'm fully aware that a transaction is likely to be open: for example, an application process failed mid-transaction, and the transaction was neither rolled back nor closed before the process terminated. If the process failed, however, I probably won't have access to the transaction ID.

I would like the URI of the open transaction in the body of the 409 response, so I can decide whether or not to roll it back.

**Comment by whikloj** [comment]
Hey @tomwrobel, we discussed this at today's community call and I'm wondering if you see any concern with potentially giving the transaction ID to a user that wouldn't normally know. The user would still require permissions to act on the repository, so the bad actor would already need to be "inside the house" (so to speak). But I wanted to raise this to get your thoughts.

**Comment by tomwrobel** [comment]
Hey @whikloj 

A transaction ID isn't, in itself, terribly revealing, is it? I don't know if any information could be intuited from it. If they don't have the authority to revoke or update it, then I can't see how knowing the ID itself would be an issue.

**Comment by Surfrdan** [comment]
The only risk is that a rogue user could steal the transaction ID and submit unintended requests within that transaction. It's akin to a session theft but much less damaging. We just wanted to raise it as a minor concern. If it was problematic, It could the controlled by a properties file toggle with an opt-in strategy

**Comment by tomwrobel** [comment]
One of the reasons this is relevant, btw, is that we have some LOOONG transactions in our system. If we're uploading a series of very large binary files via a copy, then it can take easily 30 minutes for a transaction to complete. Not merely do we need to keep pinging the transaction to keep it alive, but we need to set the transaction timeout quite high

**Comment by whikloj** [comment]
Hey @tomwrobel. There is a thought that you might want to have multiple users working on a transaction at the same time. But you are correct about your process with Alice and Bob above. It really doesn't even have to be malicious actions, but Bob could perform any action with the transaction up to and including committing or rolling it back.
 
>    Can a user who didn't open a transaction roll back that transaction? It seems to me that only admin level users should be able to do that

Yes, any user with a transaction ID can use it as we don't associate the transaction to a specific user.

>    Can a user who isn't authenticated (in a system configured to require authentication) open or modify a transaction at all?

No, you do need to have permissions on the `fcr:tx` endpoint for a user to open, commit or rollback a transaction.

Adding a user ID check for access to the transaction would require some work.

**Comment by whikloj** [comment]
@tomwrobel just a thought, but could your long running client print out or log the transaction ID when you open a transaction?

**Comment by whikloj** [comment]
Also, moving this to https://fedora-repository.atlassian.net/browse/FCREPO-3893

**Comment by tomwrobel** [comment]
@whikloj I can log it, but then I'm unpicking things manually, instead of having code that can say "just break the lock". It's a last ditch fallback.

I'm sure you've thought about it, but there is a potential issue here:

- process one begins a transaction on x number of objects, quite a lot of them
- process one starts a side process that refreshes/renews the transaction every minute (we used this for large uploads)
- process one dies, but the side process stays active

Now you've effectively locked those objects until, I assume, the Fedora server is restarted.

However, in answer to the general issue:

I understand that, as transactions permissions aren't granular (you need permissions to open, close, or rollback ANY transaction, but not an individual one) the option is either:

- a) transactions can only be modified by someone with that transaction's tx:id, and in effect once started will either be finished by the agent who started them or timeout OR
- b) any transaction can be stepped on by any agent who can open, commit, or rollback a transaction

If so, I think I agree that the second mode of operation is probably better. I think the straightforward solution, in any case, would be to wait out the timeout and let things roll back automatically.

**Comment by whikloj** [comment]
Hey @tomwrobel, I'm not sure what the difference is between getting the transaction ID from the process that started the transaction or from a second process that is trying to act on the resource?
In both cases you could then send a "rollback" command to undo the transaction's work.

**Comment by whikloj** [comment]
Resolved with https://github.com/fcrepo/fcrepo/commit/2563f0f7fb973387282d4e22c659a3c4a1f4f4bc
