### ISSUE TITLE
Blank screen on  :  version (6.4.6-200.fc38.x86_64) workstation 

### ISSUE THREAD

**Issue by Horiodino** [fcrepo/fcrepo#2042]
i just recently updated my fedora  to version (6.4.6-200.fc38.x86_64) workstation 
and when i am booting it up getting blank screen . i don`t  know the cause but its happening when i updated.
now i am using (6.3.8-200.fc38.x86_64) workstation.

**Comment by whikloj** [comment]
This is the repository for https://fedora.lyrasis.org/

We don't have a 6.4.6 release.
