### ISSUE TITLE
Question: Recommended viewer for H2 database and fcrepo schema

### ISSUE THREAD

**Issue by ross-spencer** [fcrepo/fcrepo#2047]
Hi All - do you have a recommended viewer for the H2 database embedded in the webapp? Additionally, default connection settings and schema?

**Comment by pwinckles** [comment]
@ross-spencer You can connect to the H2 db by:

1. Downloading a copy of h2 (needs to match the version used by the version of fedora that you're using, which is 2.1.210 for the latest release): https://mvnrepository.com/artifact/com.h2database/h2/2.1.210
2. Launch the h2 web console (this should open a webpage in your browser): `java -jar h2-2.1.210.jar`
3. Open the db by specifying the jdbc url, for example `jdbc:h2:/home/pwinckles/Downloads/fcrepo/fcrepo-home/data/fcrepo-h2`. When you start fedora, there should be a log line like `(DatabaseConfig) JDBC URL:...`. Copy the value from there.
4. Remove the default user name
5. Click "connect"

Note, you can't have fedora running when you connect to the db.

**Comment by ross-spencer** [comment]
Thanks @pwinckles I will give this a go!

**Comment by whikloj** [comment]
Thank you @pwinckles, I'll make a page for this in the wiki too.
