### ISSUE TITLE
FCREPO needs to be updated because of the ActiveMQ security event

### ISSUE THREAD

**Issue by noahwsmith** [fcrepo/fcrepo#2062]
https://github.com/fcrepo/fcrepo/releases/tag/fcrepo-6.4.1

See https://fedora-repository.atlassian.net/browse/FCREPO-3911

**Comment by Surfrdan** [comment]
Thanks Noah. This release work has been completed and the community has been notified through as many channels as possible. I'm going to close this issue now as It's no longer active
